### PR TITLE
upgrade to evdi 1.14.5, fixes #272

### LINKED ISSUE #272: evdi module doesn't build against Fedora 40 kernel 6.10
The evdi module doesn't build against the latest kernel 6.10.3 on Fedora 40.

Output of `uname -a`:

```
Linux phalaenopsis 6.10.3-200.fc40.x86_64 #1 SMP PREEMPT_DYNAMIC Mon Aug  5 14:30:00 UTC 2024 x86_64 GNU/Linux
```

Contents of `/var/log/displaylink/displaylink.log`:

```
Building module:
Cleaning build area...
Building module(s)...(bad exit status: 2)
Failed command:
make -j14 KERNELRELEASE=6.10.3-200.fc40.x86_64 all INCLUDEDIR=/lib/modules/6.10.3-200.fc40.x86_64/build/include KVERSION=6.10.3-200.fc40.x86_64 DKMS_BUILD=1
Error! Bad return status for module build on kernel: 6.10.3-200.fc40.x86_64 (x86_64)
Consult /var/lib/dkms/evdi/1.14.4/build/make.log for more information.
```

Tail of `/var/lib/dkms/evdi/1.14.4/build/make.log`:

```
# CC [M]  /var/lib/dkms/evdi/1.14.4/build/evdi_ioc32.o
  gcc -Wp,-MMD,/var/lib/dkms/evdi/1.14.4/build/.evdi_ioc32.o.d -nostdinc -I./arch/x86/include -I./arch/x86/include/generated  -I./include -I./arch/x86/include/uapi -I./arch/x86/>
/var/lib/dkms/evdi/1.14.4/build/evdi_gem.c: In function ‘evdi_gem_vmap’:
/var/lib/dkms/evdi/1.14.4/build/evdi_gem.c:319:25: error: implicit declaration of function ‘vmap’; did you mean ‘kmap’? [-Wimplicit-function-declaration]
  319 |         obj->vmapping = vmap(obj->pages, page_count, 0, PAGE_KERNEL);
      |                         ^~~~
      |                         kmap
/var/lib/dkms/evdi/1.14.4/build/evdi_gem.c:319:23: error: assignment to ‘void *’ from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
  319 |         obj->vmapping = vmap(obj->pages, page_count, 0, PAGE_KERNEL);
      |                       ^
/var/lib/dkms/evdi/1.14.4/build/evdi_gem.c: In function ‘evdi_gem_vunmap’:
/var/lib/dkms/evdi/1.14.4/build/evdi_gem.c:355:17: error: implicit declaration of function ‘vunmap’; did you mean ‘kunmap’? [-Wimplicit-function-declaration]
  355 |                 vunmap(obj->vmapping);
      |                 ^~~~~~
      |                 kunmap
make[3]: *** [scripts/Makefile.build:244: /var/lib/dkms/evdi/1.14.4/build/evdi_gem.o] Error 1
make[3]: *** Waiting for unfinished jobs....
make[2]: *** [/usr/src/kernels/6.10.3-200.fc40.x86_64/Makefile:1946: /var/lib/dkms/evdi/1.14.4/build] Error 2
make[1]: *** [Makefile:252: __sub-make] Error 2
make[1]: Leaving directory '/usr/src/kernels/6.10.3-200.fc40.x86_64'
make: *** [Makefile:38: all] Error 2
```

### PR DESCRIPTION
**Pull request by benkay86**

### CODE REVIEW

**Review by mitmarcus — APPROVED** [review]

**Comment by kalkin** [comment]
works for me

**Comment by kharyam** [comment]
works for me too

**Comment by benkay86** [comment]
This PR is superseded by the upgrade to upstream evdi 1.14.6 [fbfbf52](https://github.com/displaylink-rpm/displaylink-rpm/commit/fbfbf52433d5fce4b57801fe7f17c5894c3491ac).
