### ISSUE TITLE
Building EVDI fails with kernel 5.11+

### ISSUE THREAD

**Issue by qoheniac** [displaylink-rpm/displaylink-rpm#161]
Hi, I'm on Fedora 33 with kernel 5.11.7 and installing the RPM package for DisplayLink 1.7.2 fails during the building procedure for EVDI 1.7.2. The log files seem to suggest I should go to `/usr/src/kernels/5.11.7-200.fc33.x86_64` and run `make oldconfig && make prepare`, but as I have no idea what those commands do, I opened this issue looking for help. Thank you in advance!

```
$ cat /var/log/displaylink/displaylink.log
DKMS: add completed.

Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area....
make -j4 KERNELRELEASE=5.11.7-200.fc33.x86_64 all INCLUDEDIR=/lib/modules/5.11.7-200.fc33.x86_64/build/include KVERSION=5.11.7-200.fc33.x86_64 DKMS_BUILD=1....(bad exit status: 2)
Error! Bad return status for module build on kernel: 5.11.7-200.fc33.x86_64 (x86_64)
Consult /var/lib/dkms/evdi/1.7.2/build/make.log for more information.

Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area....
make -j4 KERNELRELEASE=5.11.7-200.fc33.x86_64 all INCLUDEDIR=/lib/modules/5.11.7-200.fc33.x86_64/build/include KVERSION=5.11.7-200.fc33.x86_64 DKMS_BUILD=1....(bad exit status: 2)
Error! Bad return status for module build on kernel: 5.11.7-200.fc33.x86_64 (x86_64)
Consult /var/lib/dkms/evdi/1.7.2/build/make.log for more information.

------------------------------
Deleting module version: 1.7.2
completely from the DKMS tree.
------------------------------
Done.

Creating symlink /var/lib/dkms/evdi/1.7.2/source ->
                 /usr/src/evdi-1.7.2

DKMS: add completed.

Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area....
make -j4 KERNELRELEASE=5.11.7-200.fc33.x86_64 all INCLUDEDIR=/lib/modules/5.11.7-200.fc33.x86_64/build/include KVERSION=5.11.7-200.fc33.x86_64 DKMS_BUILD=1....(bad exit status: 2)
Error! Bad return status for module build on kernel: 5.11.7-200.fc33.x86_64 (x86_64)
Consult /var/lib/dkms/evdi/1.7.2/build/make.log for more information.

Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area....
make -j4 KERNELRELEASE=5.11.7-200.fc33.x86_64 all INCLUDEDIR=/lib/modules/5.11.7-200.fc33.x86_64/build/include KVERSION=5.11.7-200.fc33.x86_64 DKMS_BUILD=1....(bad exit status: 2)
Error! Bad return status for module build on kernel: 5.11.7-200.fc33.x86_64 (x86_64)
Consult /var/lib/dkms/evdi/1.7.2/build/make.log for more information.
```

```
$ cat /var/lib/dkms/evdi/1.7.2/build/make.log
DKMS make.log for evdi-1.7.2 for kernel 5.11.7-200.fc33.x86_64 (x86_64)
Mo 22. Mär 22:29:46 CET 2021
make KBUILD_VERBOSE=1 M=/var/lib/dkms/evdi/1.7.2/build SUBDIRS=/var/lib/dkms/evdi/1.7.2/build SRCROOT=/var/lib/dkms/evdi/1.7.2/build CONFIG_MODULE_SIG= -C /lib/modules/5.11.7-200.fc33.x86_64/build modules
make[1]: Entering directory '/usr/src/kernels/5.11.7-200.fc33.x86_64'
test -e include/generated/autoconf.h -a -e include/config/auto.conf || (		\
echo >&2;							\
echo >&2 "  ERROR: Kernel configuration is invalid.";		\
echo >&2 "         include/generated/autoconf.h or include/config/auto.conf are missing.";\
echo >&2 "         Run 'make oldconfig && make prepare' on kernel src to fix it.";	\
echo >&2 ;							\
/bin/false)
make -f ./scripts/Makefile.build obj=/var/lib/dkms/evdi/1.7.2/build \
single-build= \
need-builtin=1 need-modorder=1
  gcc -Wp,-MMD,/var/lib/dkms/evdi/1.7.2/build/.evdi_drv.o.d -nostdinc -isystem /usr/lib/gcc/x86_64-redhat-linux/10/include -I./arch/x86/include -I./arch/x86/include/generated  -I./include -I./arch/x86/include/uapi -I./arch/x86/include/generated/uapi -I./include/uapi -I./include/generated/uapi -include ./include/linux/kconfig.h -include ./include/linux/compiler_types.h -D__KERNEL__ -fmacro-prefix-map=./= -Wall -Wundef -Werror=strict-prototypes -Wno-trigraphs -fno-strict-aliasing -fno-common -fshort-wchar -fno-PIE -Werror=implicit-function-declaration -Werror=implicit-int -Wno-address-of-packed-member -Werror=return-type -Wno-format-security -std=gnu89 -mno-sse -mno-mmx -mno-sse2 -mno-3dnow -mno-avx -fcf-protection=none -m64 -falign-jumps=1 -falign-loops=1 -mno-80387 -mno-fp-ret-in-387 -mpreferred-stack-boundary=3 -mskip-rax-setup -mtune=generic -mno-red-zone -mcmodel=kernel -Wno-sign-compare -fno-asynchronous-unwind-tables -mindirect-branch=thunk-extern -mindirect-branch-register -fno-jump-tables -fno-delete-null-pointer-checks -Wno-frame-address -Wno-format-truncation -Wno-format-overflow -Wno-address-of-packed-member -O2 -fno-allow-store-data-races -Wframe-larger-than=2048 -fstack-protector -Wno-unused-but-set-variable -Wimplicit-fallthrough -Wno-unused-const-variable -g -pg -mrecord-mcount -mfentry -DCC_USING_FENTRY -Wdeclaration-after-statement -Wvla -Wno-pointer-sign -Wno-stringop-truncation -Wno-zero-length-bounds -Wno-array-bounds -Wno-stringop-overflow -Wno-restrict -Wno-maybe-uninitialized -fno-strict-overflow -fno-stack-check -fconserve-stack -Werror=date-time -Werror=incompatible-pointer-types -Werror=designated-init -Wno-packed-not-aligned -Iinclude/drm  -DMODULE  -DKBUILD_BASENAME='"evdi_drv"' -DKBUILD_MODNAME='"evdi"' -c -o /var/lib/dkms/evdi/1.7.2/build/evdi_drv.o /var/lib/dkms/evdi/1.7.2/build/evdi_drv.c
  gcc -Wp,-MMD,/var/lib/dkms/evdi/1.7.2/build/.evdi_modeset.o.d -nostdinc -isystem /usr/lib/gcc/x86_64-redhat-linux/10/include -I./arch/x86/include -I./arch/x86/include/generated  -I./include -I./arch/x86/include/uapi -I./arch/x86/include/generated/uapi -I./include/uapi -I./include/generated/uapi -include ./include/linux/kconfig.h -include ./include/linux/compiler_types.h -D__KERNEL__ -fmacro-prefix-map=./= -Wall -Wundef -Werror=strict-prototypes -Wno-trigraphs -fno-strict-aliasing -fno-common -fshort-wchar -fno-PIE -Werror=implicit-function-declaration -Werror=implicit-int -Wno-address-of-packed-member -Werror=return-type -Wno-format-security -std=gnu89 -mno-sse -mno-mmx -mno-sse2 -mno-3dnow -mno-avx -fcf-protection=none -m64 -falign-jumps=1 -falign-loops=1 -mno-80387 -mno-fp-ret-in-387 -mpreferred-stack-boundary=3 -mskip-rax-setup -mtune=generic -mno-red-zone -mcmodel=kernel -Wno-sign-compare -fno-asynchronous-unwind-tables -mindirect-branch=thunk-extern -mindirect-branch-register -fno-jump-tables -fno-delete-null-pointer-checks -Wno-frame-address -Wno-format-truncation -Wno-format-overflow -Wno-address-of-packed-member -O2 -fno-allow-store-data-races -Wframe-larger-than=2048 -fstack-protector -Wno-unused-but-set-variable -Wimplicit-fallthrough -Wno-unused-const-variable -g -pg -mrecord-mcount -mfentry -DCC_USING_FENTRY -Wdeclaration-after-statement -Wvla -Wno-pointer-sign -Wno-stringop-truncation -Wno-zero-length-bounds -Wno-array-bounds -Wno-stringop-overflow -Wno-restrict -Wno-maybe-uninitialized -fno-strict-overflow -fno-stack-check -fconserve-stack -Werror=date-time -Werror=incompatible-pointer-types -Werror=designated-init -Wno-packed-not-aligned -Iinclude/drm  -DMODULE  -DKBUILD_BASENAME='"evdi_modeset"' -DKBUILD_MODNAME='"evdi"' -c -o /var/lib/dkms/evdi/1.7.2/build/evdi_modeset.o /var/lib/dkms/evdi/1.7.2/build/evdi_modeset.c
  gcc -Wp,-MMD,/var/lib/dkms/evdi/1.7.2/build/.evdi_connector.o.d -nostdinc -isystem /usr/lib/gcc/x86_64-redhat-linux/10/include -I./arch/x86/include -I./arch/x86/include/generated  -I./include -I./arch/x86/include/uapi -I./arch/x86/include/generated/uapi -I./include/uapi -I./include/generated/uapi -include ./include/linux/kconfig.h -include ./include/linux/compiler_types.h -D__KERNEL__ -fmacro-prefix-map=./= -Wall -Wundef -Werror=strict-prototypes -Wno-trigraphs -fno-strict-aliasing -fno-common -fshort-wchar -fno-PIE -Werror=implicit-function-declaration -Werror=implicit-int -Wno-address-of-packed-member -Werror=return-type -Wno-format-security -std=gnu89 -mno-sse -mno-mmx -mno-sse2 -mno-3dnow -mno-avx -fcf-protection=none -m64 -falign-jumps=1 -falign-loops=1 -mno-80387 -mno-fp-ret-in-387 -mpreferred-stack-boundary=3 -mskip-rax-setup -mtune=generic -mno-red-zone -mcmodel=kernel -Wno-sign-compare -fno-asynchronous-unwind-tables -mindirect-branch=thunk-extern -mindirect-branch-register -fno-jump-tables -fno-delete-null-pointer-checks -Wno-frame-address -Wno-format-truncation -Wno-format-overflow -Wno-address-of-packed-member -O2 -fno-allow-store-data-races -Wframe-larger-than=2048 -fstack-protector -Wno-unused-but-set-variable -Wimplicit-fallthrough -Wno-unused-const-variable -g -pg -mrecord-mcount -mfentry -DCC_USING_FENTRY -Wdeclaration-after-statement -Wvla -Wno-pointer-sign -Wno-stringop-truncation -Wno-zero-length-bounds -Wno-array-bounds -Wno-stringop-overflow -Wno-restrict -Wno-maybe-uninitialized -fno-strict-overflow -fno-stack-check -fconserve-stack -Werror=date-time -Werror=incompatible-pointer-types -Werror=designated-init -Wno-packed-not-aligned -Iinclude/drm  -DMODULE  -DKBUILD_BASENAME='"evdi_connector"' -DKBUILD_MODNAME='"evdi"' -c -o /var/lib/dkms/evdi/1.7.2/build/evdi_connector.o /var/lib/dkms/evdi/1.7.2/build/evdi_connector.c
  gcc -Wp,-MMD,/var/lib/dkms/evdi/1.7.2/build/.evdi_encoder.o.d -nostdinc -isystem /usr/lib/gcc/x86_64-redhat-linux/10/include -I./arch/x86/include -I./arch/x86/include/generated  -I./include -I./arch/x86/include/uapi -I./arch/x86/include/generated/uapi -I./include/uapi -I./include/generated/uapi -include ./include/linux/kconfig.h -include ./include/linux/compiler_types.h -D__KERNEL__ -fmacro-prefix-map=./= -Wall -Wundef -Werror=strict-prototypes -Wno-trigraphs -fno-strict-aliasing -fno-common -fshort-wchar -fno-PIE -Werror=implicit-function-declaration -Werror=implicit-int -Wno-address-of-packed-member -Werror=return-type -Wno-format-security -std=gnu89 -mno-sse -mno-mmx -mno-sse2 -mno-3dnow -mno-avx -fcf-protection=none -m64 -falign-jumps=1 -falign-loops=1 -mno-80387 -mno-fp-ret-in-387 -mpreferred-stack-boundary=3 -mskip-rax-setup -mtune=generic -mno-red-zone -mcmodel=kernel -Wno-sign-compare -fno-asynchronous-unwind-tables -mindirect-branch=thunk-extern -mindirect-branch-register -fno-jump-tables -fno-delete-null-pointer-checks -Wno-frame-address -Wno-format-truncation -Wno-format-overflow -Wno-address-of-packed-member -O2 -fno-allow-store-data-races -Wframe-larger-than=2048 -fstack-protector -Wno-unused-but-set-variable -Wimplicit-fallthrough -Wno-unused-const-variable -g -pg -mrecord-mcount -mfentry -DCC_USING_FENTRY -Wdeclaration-after-statement -Wvla -Wno-pointer-sign -Wno-stringop-truncation -Wno-zero-length-bounds -Wno-array-bounds -Wno-stringop-overflow -Wno-restrict -Wno-maybe-uninitialized -fno-strict-overflow -fno-stack-check -fconserve-stack -Werror=date-time -Werror=incompatible-pointer-types -Werror=designated-init -Wno-packed-not-aligned -Iinclude/drm  -DMODULE  -DKBUILD_BASENAME='"evdi_encoder"' -DKBUILD_MODNAME='"evdi"' -c -o /var/lib/dkms/evdi/1.7.2/build/evdi_encoder.o /var/lib/dkms/evdi/1.7.2/build/evdi_encoder.c
/var/lib/dkms/evdi/1.7.2/build/evdi_drv.c:90:3: error: ‘struct drm_driver’ has no member named ‘preclose’; did you mean ‘postclose’?
   90 |  .preclose = evdi_driver_preclose,
      |   ^~~~~~~~
      |   postclose
/var/lib/dkms/evdi/1.7.2/build/evdi_drv.c:90:14: error: initialization of ‘void (*)(struct drm_device *)’ from incompatible pointer type ‘void (*)(struct drm_device *, struct drm_file *)’ [-Werror=incompatible-pointer-types]
   90 |  .preclose = evdi_driver_preclose,
      |              ^~~~~~~~~~~~~~~~~~~~
/var/lib/dkms/evdi/1.7.2/build/evdi_drv.c:90:14: note: (near initialization for ‘driver.release’)
/var/lib/dkms/evdi/1.7.2/build/evdi_drv.c:96:3: error: ‘struct drm_driver’ has no member named ‘gem_free_object_unlocked’
   96 |  .gem_free_object_unlocked = evdi_gem_free_object,
      |   ^~~~~~~~~~~~~~~~~~~~~~~~
/var/lib/dkms/evdi/1.7.2/build/evdi_drv.c:96:30: error: initialization of ‘void (*)(struct drm_device *)’ from incompatible pointer type ‘void (*)(struct drm_gem_object *)’ [-Werror=incompatible-pointer-types]
   96 |  .gem_free_object_unlocked = evdi_gem_free_object,
      |                              ^~~~~~~~~~~~~~~~~~~~
/var/lib/dkms/evdi/1.7.2/build/evdi_drv.c:96:30: note: (near initialization for ‘driver.lastclose’)
/var/lib/dkms/evdi/1.7.2/build/evdi_drv.c:100:3: error: ‘struct drm_driver’ has no member named ‘gem_vm_ops’
  100 |  .gem_vm_ops = &evdi_gem_vm_ops,
      |   ^~~~~~~~~~
/var/lib/dkms/evdi/1.7.2/build/evdi_drv.c:100:16: error: initialization of ‘void (*)(struct drm_device *)’ from incompatible pointer type ‘const struct vm_operations_struct *’ [-Werror=incompatible-pointer-types]
  100 |  .gem_vm_ops = &evdi_gem_vm_ops,
      |                ^
/var/lib/dkms/evdi/1.7.2/build/evdi_drv.c:100:16: note: (near initialization for ‘driver.unload’)
/var/lib/dkms/evdi/1.7.2/build/evdi_drv.c:114:3: error: ‘struct drm_driver’ has no member named ‘gem_prime_export’; did you mean ‘gem_prime_import’?
  114 |  .gem_prime_export = drm_gem_prime_export,
      |   ^~~~~~~~~~~~~~~~
      |   gem_prime_import
/var/lib/dkms/evdi/1.7.2/build/evdi_drv.c:114:22: error: initialization of ‘int (*)(struct drm_device *, struct drm_file *, int,  uint32_t *)’ {aka ‘int (*)(struct drm_device *, struct drm_file *, int,  unsigned int *)’} from incompatible pointer type ‘struct dma_buf * (*)(struct drm_gem_object *, int)’ [-Werror=incompatible-pointer-types]
  114 |  .gem_prime_export = drm_gem_prime_export,
      |                      ^~~~~~~~~~~~~~~~~~~~
/var/lib/dkms/evdi/1.7.2/build/evdi_drv.c:114:22: note: (near initialization for ‘driver.prime_fd_to_handle’)
/var/lib/dkms/evdi/1.7.2/build/evdi_drv.c:115:3: error: ‘struct drm_driver’ has no member named ‘gem_prime_get_sg_table’; did you mean ‘gem_prime_import_sg_table’?
  115 |  .gem_prime_get_sg_table = evdi_prime_get_sg_table,
      |   ^~~~~~~~~~~~~~~~~~~~~~
      |   gem_prime_import_sg_table
/var/lib/dkms/evdi/1.7.2/build/evdi_drv.c:115:28: error: initialization of ‘struct drm_gem_object * (*)(struct drm_device *, struct dma_buf *)’ from incompatible pointer type ‘struct sg_table * (*)(struct drm_gem_object *)’ [-Werror=incompatible-pointer-types]
  115 |  .gem_prime_get_sg_table = evdi_prime_get_sg_table,
      |                            ^~~~~~~~~~~~~~~~~~~~~~~
/var/lib/dkms/evdi/1.7.2/build/evdi_drv.c:115:28: note: (near initialization for ‘driver.gem_prime_import’)
/var/lib/dkms/evdi/1.7.2/build/evdi_drv.c:118:3: error: ‘struct drm_driver’ has no member named ‘enable_vblank’
  118 |  .enable_vblank = evdi_enable_vblank,
      |   ^~~~~~~~~~~~~
/var/lib/dkms/evdi/1.7.2/build/evdi_drv.c:118:19: error: initialization of ‘int (*)(struct drm_gem_object *, struct vm_area_struct *)’ from incompatible pointer type ‘int (*)(struct drm_device *, unsigned int)’ [-Werror=incompatible-pointer-types]
  118 |  .enable_vblank = evdi_enable_vblank,
      |                   ^~~~~~~~~~~~~~~~~~
/var/lib/dkms/evdi/1.7.2/build/evdi_drv.c:118:19: note: (near initialization for ‘driver.gem_prime_mmap’)
/var/lib/dkms/evdi/1.7.2/build/evdi_drv.c:119:3: error: ‘struct drm_driver’ has no member named ‘disable_vblank’
  119 |  .disable_vblank = evdi_disable_vblank,
      |   ^~~~~~~~~~~~~~
/var/lib/dkms/evdi/1.7.2/build/evdi_drv.c:119:20: error: initialization of ‘int (*)(struct drm_file *, struct drm_device *, struct drm_mode_create_dumb *)’ from incompatible pointer type ‘void (*)(struct drm_device *, unsigned int)’ [-Werror=incompatible-pointer-types]
  119 |  .disable_vblank = evdi_disable_vblank,
      |                    ^~~~~~~~~~~~~~~~~~~
/var/lib/dkms/evdi/1.7.2/build/evdi_drv.c:119:20: note: (near initialization for ‘driver.dumb_create’)
/var/lib/dkms/evdi/1.7.2/build/evdi_modeset.c:167:20: error: initialization of ‘void (*)(struct drm_crtc *, struct drm_atomic_state *)’ from incompatible pointer type ‘void (*)(struct drm_crtc *, struct drm_crtc_state *)’ [-Werror=incompatible-pointer-types]
  167 |  .atomic_flush   = evdi_crtc_atomic_flush,
      |                    ^~~~~~~~~~~~~~~~~~~~~~
/var/lib/dkms/evdi/1.7.2/build/evdi_modeset.c:167:20: note: (near initialization for ‘evdi_helper_funcs.atomic_flush’)
cc1: some warnings being treated as errors
make[2]: *** [scripts/Makefile.build:279: /var/lib/dkms/evdi/1.7.2/build/evdi_drv.o] Error 1
make[2]: *** Waiting for unfinished jobs....
   ./tools/objtool/objtool orc generate  --module --no-fp --retpoline --uaccess /var/lib/dkms/evdi/1.7.2/build/evdi_encoder.o
   ./tools/objtool/objtool orc generate  --module --no-fp --retpoline --uaccess /var/lib/dkms/evdi/1.7.2/build/evdi_connector.o
cc1: some warnings being treated as errors
make[2]: *** [scripts/Makefile.build:279: /var/lib/dkms/evdi/1.7.2/build/evdi_modeset.o] Error 1
make[1]: *** [Makefile:1807: /var/lib/dkms/evdi/1.7.2/build] Error 2
make[1]: Leaving directory '/usr/src/kernels/5.11.7-200.fc33.x86_64'
make: *** [Makefile:28: all] Error 2
```

**Comment by elguero** [comment]
Please see this comment from DisplayLink: https://github.com/DisplayLink/evdi/pull/256#issuecomment-787848715

There currently is no official support for kernel 5.11

**Comment by qoheniac** [comment]
Thank you, for your quick reply. I'll subscribe to that issue and wait.

**Comment by Chosco** [comment]
I have exactly the same problem: After upgrading to fedora 33, the monitor on my docking station no longer works because my fedora has a 5.11.11 kernel.

Thank you for now for the great software.
I am sorry that I cannot help to implement kernel version 5.11.

**Comment by elguero** [comment]
Here is an update from Displaylink on the issue with kernel 5.11+.

https://github.com/DisplayLink/evdi/issues/275

**Comment by bnavigator** [comment]
FYI: DisplayLink 2.4.0 has been released, which also bundles the second to last commit of evdi on the devel branch (1.9.1 plus 4 commits). It works with Kernel 5.11.

**Comment by jteib** [comment]
> FYI: DisplayLink 2.4.0 has been released, which also bundles the second to last commit of evdi on the devel branch (1.9.1 plus 4 commits). It works with Kernel 5.11.

Shouldn't we see a new release then?  Looks like the latest release is still v5.3.1-1

**Comment by elguero** [comment]
@jteib Yes, it is being worked on.

**Comment by jteib** [comment]
Got it.  Didn't mean to sound pushy or impatient, just curious.  Thanks for the great work!!

**Comment by gabops** [comment]
Hello there,

My dockstation with two displays was not working after moving to Fedora 33. I tried to use the latest rpm package for it that this repo provides with no luck. Fortunately, I've been able to get everything working on Fedora 33 with kernel "**5.11.13-200**" (the latest installed today after a dnf update) by installing the driver from the official package (5.4 version that supports kernels 5.11 and 5.12). I did the following:

1. Install dkms
```bash
$ dnf install dkms
```
2. Download the driver at https://www.synaptics.com/products/displaylink-graphics/downloads/ubuntu
3. Extract the content of the file by doing:
```bash
$ chmod u+x displaylink-driver-5.4.0-55.153.run
$ ./displaylink-driver-5.4.0-55.153.run --noexec --keep
```
4. Move into the directory created as a result of the extraction:
```bash
$ cd displaylink-driver-5.4.0-55.153
```
5. Now open the script file called "displaylink-installer.sh" and go to the function defined on line 529 called "chedk_libdrm" and do the following:
```bash
check_libdrm()
{
  #hash apt 2>/dev/null || return
  #apt list -qq --installed libdrm-dev 2>/dev/null | grep -q libdrm-dev
  return 0
}
```
6. Finally, run the script **as root** with:
```bash
$ sudo ./displaylink-installer.sh
```


Everything is working flawlessly and I am quite happy with the performance. Ironically, despite the official driver supports only Ubuntu 20.04, the driver works far much better on Fedora in terms of FPS and cpu consumed by the displaylink process itself. 

Hope you find this helpful.


Regards.

**Comment by elguero** [comment]
Thank you for sharing.

This is what we are waiting on from DisplayLink to see if it saves us time from having to change the current process we have in place.

https://github.com/DisplayLink/evdi/issues/275#issuecomment-815955502

**Comment by jteib** [comment]
It seems displaylink-installer.sh has a few more functions aside from check_libdrm() that are Ubuntu specific, and look for the services init directories.  I was not able to get it to install on Fedora 33 by simply editing the displaylink-installer.sh as shown above.

**Comment by elguero** [comment]
Correct.  That is why this project is specific to Fedora and does not use the installer at all.

**Comment by brego81** [comment]
Thanks @gabops for the solution, it works for me despite I see an error in the installation process:

```
$  sudo ./displaylink-installer.sh
DisplayLink Linux Software 5.4.0-55.153 install script called: 
Distribution discovered: "Fedora release 33 (Thirty Three)"

Installing

[ Installing EVDI ]
[[ Installing EVDI DKMS module ]]

Creating symlink /var/lib/dkms/evdi/1.9.1/source ->
                 /usr/src/evdi-1.9.1

DKMS: add completed.

Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area...
make -j8 KERNELRELEASE=5.11.13-200.fc33.x86_64 all INCLUDEDIR=/lib/modules/5.11.13-200.fc33.x86_64/build/include KVERSION=5.11.13-200.fc33.x86_64 DKMS_BUILD=1.....
cleaning build area...

DKMS: build completed.

evdi.ko.xz:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/5.11.13-200.fc33.x86_64/extra/
Adding any weak-modules

depmod.....

DKMS: install completed.
[[ Installing module configuration files ]]
[[ Installing EVDI library ]]
cc -I../module -std=gnu99 -fPIC -D_FILE_OFFSET_BITS=64    -c -o evdi_lib.o evdi_lib.c
evdi_lib.c:6:10: fatal error: libdrm/drm.h: No such file or directory
    6 | #include <libdrm/drm.h>
      |          ^~~~~~~~~~~~~~
compilation terminated.
make: *** [<builtin>: evdi_lib.o] Error 1
ERROR: Failed to build evdi library.
```

**Comment by jteib** [comment]
How are you getting this Ubuntu script to work with Fedora by only following @gabops steps above?

**Comment by gabops** [comment]
Hello,

I've tried again on a virtual machine over a fresh Fedora 33 installation and I was able to install evdi again. The only difference is that I had to install "libdrm-devel" package. I am pretty sure I overlooked the entry in my bash history when writing the instructions for my original message. I edited it. Sorry for that.

**Comment by jteib** [comment]
@gabops no worries, I figured out my issue.  In my case, I am running a Fedora spin with xfce desktop.  The lsb_release that the detect_distro() function uses was not present.  After installing redhat-lsb-core, the script executed and finished successfully!  

After that I created a new MOK key, signed for this kernel and my extra monitor is back!

Thanks for your help!

**Comment by elguero** [comment]
Since we are not getting a response back from DisplayLInk as to whether they plan to make an official release of the EVDI library and kernel module that works with kernels 5.11 / 5.12, I have come up with an approach to solve this for now.

I submitted a PR a couple of days ago to get feedback (https://github.com/displaylink-rpm/displaylink-rpm/pull/163).  My thoughts are to use the EVDI tarball that is included in the DisplayLink 5.4 drivers package.  This way we can release new RPM builds that work with kernels 5.11 / 5.12.  I have also adjusted the build to allow for us to pull from the EVDI repo here on GitHub by using `make unbundled`, which can be used more for testing and development purposes.

What is everyone's thoughts on this approach?

Should we stick to the way we are doing things and hope that DisplayLink will eventually tag a proper working release on their repo?

Or, should we just get a release out that we know is working so that everyone can get their work setups back?

Thank you

**Comment by davidschenz** [comment]
Howdy - I built the branch this afternoon and it's worked fine so far on Fedora 33 with kernel 5.11.15-200. It's silly that DisplayLink won't tag the release in the branch, but until they do that, using the tarball from the drivers package makes the most sense.

Also - thank you for maintaining this project. It certainly makes my life better being able to use the extra DisplayLink screen with Fedora.

**Comment by Phaestion** [comment]
Hi everyone! Yeah, I agree with the approach of using the tarball to get a release out. I look forward to the release!
