### ISSUE TITLE
evdi does not compile with kernel 6.6.2

### ISSUE THREAD

**Issue by mschuene7** [displaylink-rpm/displaylink-rpm#256]
I was using the evdi module to access external monitors via a desplayLink device. However, when I recently installed kernel 6.6.2, the module is not being built any more. The the make log I get the following.

```
# CC [M]  /var/lib/dkms/evdi/1.14.1/build/evdi_ioc32.o
  gcc -Wp,-MMD,/var/lib/dkms/evdi/1.14.1/build/.evdi_ioc32.o.d -nostdinc -I./arch/x86/include -I./arch/x86/include/generated  -I./include -I./arch/x86/include/uapi -I./arch/x86/include/generated/uapi -I./include/uapi -I./include/generat>
/var/lib/dkms/evdi/1.14.1/build/evdi_fb.c: In function ‘evdifb_create’:
/var/lib/dkms/evdi/1.14.1/build/evdi_fb.c:421:23: error: ‘FBINFO_DEFAULT’ undeclared (first use in this function)
  421 |         info->flags = FBINFO_DEFAULT;
      |                       ^~~~~~~~~~~~~~
/var/lib/dkms/evdi/1.14.1/build/evdi_fb.c:421:23: note: each undeclared identifier is reported only once for each function it appears in
make[3]: *** [scripts/Makefile.build:243: /var/lib/dkms/evdi/1.14.1/build/evdi_fb.o] Error 1
make[3]: *** Waiting for unfinished jobs....
/var/lib/dkms/evdi/1.14.1/build/evdi_drm_drv.c:127:31: error: ‘drm_gem_prime_fd_to_handle’ undeclared here (not in a function)
  127 |         .prime_fd_to_handle = drm_gem_prime_fd_to_handle,
      |                               ^~~~~~~~~~~~~~~~~~~~~~~~~~
/var/lib/dkms/evdi/1.14.1/build/evdi_drm_drv.c:129:31: error: ‘drm_gem_prime_handle_to_fd’ undeclared here (not in a function)
  129 |         .prime_handle_to_fd = drm_gem_prime_handle_to_fd,
      |                               ^~~~~~~~~~~~~~~~~~~~~~~~~~
make[3]: *** [scripts/Makefile.build:243: /var/lib/dkms/evdi/1.14.1/build/evdi_drm_drv.o] Error 1
make[2]: *** [/usr/src/kernels/6.6.2-201.fc39.x86_64/Makefile:1931: /var/lib/dkms/evdi/1.14.1/build] Error 2
make[1]: *** [Makefile:246: __sub-make] Error 2
make[1]: Leaving directory '/usr/src/kernels/6.6.2-201.fc39.x86_64'
make: *** [Makefile:38: all] Error 2
```

With the older kernel 6.5.12 all worked fine - even on F39. It seems there has been an incompatible change in the kernel. This does not look like something I can easily get around. 

Will be there a solution soon ? 

Thank you
Malte
